import {makeStyles, normalize} from '@rneui/themed';
import {StyleSheet} from 'react-native';

const useStyles = makeStyles(({colors}) => ({
  container: {
    flex: 1,
  },
  wrapper: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.background,
  },

  body: {
    flex: 1,
    padding: normalize(24),
  },
  marginHeader: {
    marginHorizontal: normalize(24),
    marginTop: normalize(26),
  },
  viewCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  textTitleOTPV: {
    fontFamily: 'Urbanist',
    fontWeight: '700',
    fontStyle: 'normal',
    fontSize: normalize(24),
    color: colors.black,
    marginTop: normalize(34),
    lineHeight: normalize(48),
    letterSpacing: normalize(0.12),
  },
  text1: {
    marginTop: normalize(12),
    marginBottom: normalize(32),
    marginHorizontal: normalize(24),
    color: colors.black,
    fontFamily: 'Urbanist',
    fontSize: normalize(18),
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: normalize(25.2),
    letterSpacing: normalize(0.2),
  },
  viewRow: {
    flexDirection: 'row',
  },
  textOTP: {
    width: normalize(64),
    height: normalize(64),
    borderWidth: normalize(1),
    borderColor: 'black',
    borderRadius: normalize(6),
    marginEnd: normalize(16),
    textAlign: 'center',
  },
  text3: {
    marginVertical: normalize(27),
    color: colors.black,
    fontFamily: 'Urbanist',
    fontSize: normalize(18),
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: normalize(21),
    letterSpacing: normalize(0.12),
  },
  text4: {
    color: colors.black,
    fontFamily: 'Urbanist',
    fontSize: normalize(18),
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: normalize(21),
    letterSpacing: normalize(0.12),
  },
  text5: {
    color: colors.primary,
    fontFamily: 'Urbanist',
    fontSize: normalize(18),
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: normalize(21),
    letterSpacing: normalize(0.12),
  },
  textCT: {
    fontFamily: 'Urbanist',
    fontSize: normalize(18),
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: normalize(21),
    letterSpacing: normalize(0.12),
  },
  viewBottom: {
    flex: 0.93,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  btnContinue: {
    marginHorizontal: normalize(24),
    paddingHorizontal: normalize(16),
    paddingVertical: normalize(18),
    backgroundColor: colors.primary,
    shadowColor: 'rgba(248, 147, 0, 0.25)',
    shadowOffset: {
      width: normalize(4),
      height: normalize(8),
    },
    shadowRadius: normalize(24),
    shadowOpacity: normalize(1),
    borderRadius: normalize(100),
    justifyContent: 'center',
    alignItems: 'center',
    gap: normalize(10),
    alignSelf: 'stretch',
  },
  textContinue: {
    color: colors.secondary,
    textAlign: 'center',
    fontFamily: 'Urbanist',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: normalize(22.4),
    letterSpacing: normalize(0.2),
  },
}));
export default useStyles;
