export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  LOBBY = 'LOBBY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',

  SEND_OTP = 'SEND_OTP',
  CREATE_NEW_PASSWORD = 'CREATE_NEW_PASSWORD',

  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',

  PROFILE = 'PROFILE',
  BOOKMARK = 'BOOKMARK',
  EXPLORE = 'EXPLORE',
  // Profile Click 
  NOTIFICATION = 'NOTIFICATION',
  SECURITY = 'SECURITY',
  HELPCENTER = 'HELPCENTER',
  MYPROFILE = 'MYPROFILE',
  PAYMENTSMETHOD = 'PAYMENTSMETHOD',
  BECOMEVIP = 'BECOMEVIP',
  ABOUTAPP = 'ABOUTAPP',
  FAQ = 'FAQ',
  CONTACTUS = 'CONTACTUS',
  UPDATE_PROFILE2 = 'UPDATE_PROFILE2',
  TOPICS = 'TOPICS',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SEARCH = 'SEARCH',
  COMICBYTOPIC = 'COMICBYTOPIC',
  COMICDETAIL = 'COMICDETAIL',

}
