export enum routes {
  //auth
  ONBOARD = 'ONBOARD',
  SIGN_IN = 'SIGN_IN',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  LOBBY = 'LOBBY',
  UPDATE_PROFILE = 'UPDATE_PROFILE',

  SEND_OTP = 'SEND_OTP',

  BOTTOM_TAB = 'BOTTOM_TAB',
  HOME = 'HOME',

  TOPICS = 'TOPICS',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',

  PROFILE = 'PROFILE',
  BOOKMARK = 'BOOKMARK',
  EXPLORE = 'EXPLORE',
}
