export const images = {

    onboard1: require('./onboard1.json'),

    default: require('./default_avatar.png'),
    news1: require('./news1.json'),
    news2: require('./news2.json'),
    news3: require('./news3.json'),
    logo: require('./logo.json'),
    success: require('./success.json'),
    cat: require('./cat.json'),
    logo_book: require('./logo_book.png'),
    manga_dummy: require('./manga_dummy.png'),
    ic_notification: require('./ic_notification.png'),
    ic_search: require('./ic_search.png'),
    ic_Menu: require('./ic_Menu.png'),
    ic_AboutApp: require('./ic_AboutApp.png'),
    ic_HelpCenter: require('./ic_HelpCenter.png'),
    ic_Logout: require('./ic_LogOut.png'),
    ic_Notification2: require('./ic_Notification2.png'),
    ic_Security: require('./ic_Security.png'),
    ic_VIP: require('./ic_VIP.png'),
    ic_Wallet: require('./ic_Wallet.png'),
    avata: require('./avatar.jpg'),
    ic_Edit2: require('./ic_Edit2.png'),
    ic_Continue: require('./ic_Continue.png'),
    ic_Up: require('./ic_Up.png'),
    ic_Down: require('./ic_Down.png'),
    ic_Classify: require('./ic_Classify.png'),
    ic_Service: require('./ic_Service.png'),
    ic_Meta: require('./ic_Meta.png'),
    ic_Google: require('./ic_google.png'),
    ic_Website: require('./ic_Website.png'),
    ic_Facebook: require('./ic_Facebook.png'),
    ic_Add: require('./ic_Add.png'),
    ic_ZaloPay: require('./ic_Zalopay.png'),
    ic_Paypal: require('./ic_Paypal.png'),
}